#!/usr/bin/env python3
"""
Boss OS IPsec Adapter
Converts unified policy to Boss OS IPsec configuration
This is a template for custom OS implementations
"""

import os
import json
import subprocess
from pathlib import Path
from typing import Dict, Any, List
import logging


class BossOSAdapter:
    """Adapter for Boss OS IPsec implementation"""
    
    def __init__(self, config: Dict[str, Any], logger: logging.Logger = None):
        """Initialize Boss OS adapter
        
        Args:
            config: Unified IPsec policy configuration
            logger: Python logger instance
        """
        self.config = config
        self.logger = logger or logging.getLogger(__name__)
        self.global_cfg = config.get('global', {})
        self.tunnels = config.get('tunnels', [])
        self.boss_ipsec_dir = '/etc/boss-ipsec'
    
    def generate_boss_config(self) -> str:
        """Generate Boss OS IPsec configuration
        
        Returns:
            Configuration string for Boss OS
        """
        config_lines = []
        
        # Header
        config_lines.append("# Boss OS IPsec Configuration")
        config_lines.append("# Auto-generated by Unified IPsec Policy Engine")
        config_lines.append("")
        
        # Global configuration section
        config_lines.append("[global]")
        config_lines.append(f"ike_version = {self.global_cfg.get('ike_version', 'ikev2')}")
        config_lines.append(f"auth_method = {self.global_cfg.get('auth_method', 'psk')}")
        config_lines.append(f"encryption = {self.global_cfg.get('encryption', 'aes256')}")
        config_lines.append(f"integrity = {self.global_cfg.get('integrity', 'sha256')}")
        config_lines.append(f"dh_group = {self.global_cfg.get('dh_group', 14)}")
        config_lines.append(f"auto_start = {str(self.global_cfg.get('auto_start', True)).lower()}")
        config_lines.append("")
        
        # Generate tunnel sections
        for tunnel in self.tunnels:
            config_lines.extend(self._generate_tunnel_section(tunnel))
            config_lines.append("")
        
        return "\n".join(config_lines)
    
    def _generate_tunnel_section(self, tunnel: Dict[str, Any]) -> List[str]:
        """Generate configuration for a single tunnel
        
        Args:
            tunnel: Tunnel configuration dictionary
            
        Returns:
            List of configuration lines
        """
        lines = []
        tunnel_name = tunnel['name']
        
        lines.append(f"[tunnel:{tunnel_name}]")
        lines.append(f"mode = {tunnel.get('mode', 'tunnel')}")
        lines.append(f"protocol = {tunnel.get('protocol', 'esp')}")
        lines.append(f"peer_ip = {tunnel['peer_ip']}")
        
        if tunnel.get('mode') == 'tunnel':
            lines.append(f"local_subnet = {tunnel.get('local_subnet', '0.0.0.0/0')}")
            lines.append(f"remote_subnet = {tunnel.get('remote_subnet', '0.0.0.0/0')}")
        
        lines.append(f"dpd_action = {tunnel.get('dpd_action', 'restart')}")
        lines.append(f"start_action = {tunnel.get('start_action', 'start')}")
        
        return lines
    
    def generate_secrets_file(self) -> str:
        """Generate secrets/credentials file for Boss OS
        
        Returns:
            Secrets configuration string
        """
        lines = []
        lines.append("# Boss OS IPsec Secrets")
        lines.append("# Auto-generated - KEEP SECURE (600 permissions)")
        lines.append("")
        
        psk = self.global_cfg.get('psk', '')
        
        # Generate PSK entries for each tunnel
        for tunnel in self.tunnels:
            peer_ip = tunnel['peer_ip']
            lines.append(f"{peer_ip} : PSK \"{psk}\"")
        
        return "\n".join(lines)
    
    def generate_startup_script(self) -> str:
        """Generate startup/initialization script for Boss OS
        
        Returns:
            Shell script to initialize IPsec
        """
        lines = []
        
        lines.append("#!/bin/bash")
        lines.append("# Boss OS IPsec Startup Script")
        lines.append("# Auto-generated by Unified IPsec Policy Engine")
        lines.append("")
        lines.append("set -e")
        lines.append("")
        lines.append("LOG_FILE='/var/log/boss-ipsec/startup.log'")
        lines.append("echo \"$(date '+%Y-%m-%d %H:%M:%S') [INFO] Starting Boss OS IPsec...\" | tee -a $LOG_FILE")
        lines.append("")
        
        # Load kernel module if needed
        lines.append("# Load IPsec kernel module (if required)")
        lines.append("if modprobe boss_ipsec 2>/dev/null; then")
        lines.append("    echo \"$(date '+%Y-%m-%d %H:%M:%S') [INFO] IPsec kernel module loaded\" | tee -a $LOG_FILE")
        lines.append("fi")
        lines.append("")
        
        # Initialize each tunnel
        for tunnel in self.tunnels:
            tunnel_name = tunnel['name']
            peer_ip = tunnel['peer_ip']
            lines.append(f"# Initialize tunnel: {tunnel_name}")
            lines.append(f"boss-ipsec-ctl add tunnel {tunnel_name} {peer_ip} \\")
            lines.append(f"    --mode {tunnel.get('mode', 'tunnel')} \\")
            lines.append(f"    --protocol {tunnel.get('protocol', 'esp')}")
            lines.append("")
        
        lines.append("echo \"$(date '+%Y-%m-%d %H:%M:%S') [INFO] All tunnels configured\" | tee -a $LOG_FILE")
        
        return "\n".join(lines)
    
    def apply_configuration(self, dry_run: bool = True) -> bool:
        """Apply configuration to Boss OS
        
        Args:
            dry_run: If True, only show what would be done
            
        Returns:
            True if successful, False otherwise
        """
        try:
            self.logger.info("Applying Boss OS IPsec configuration...")
            
            # Generate all configuration files
            boss_config = self.generate_boss_config()
            secrets = self.generate_secrets_file()
            startup_script = self.generate_startup_script()
            
            if dry_run:
                self.logger.info("DRY RUN - Configuration would be applied as follows:")
                self.logger.info("")
                self.logger.info("=== Boss OS IPsec Configuration ===")
                self.logger.info(boss_config)
                self.logger.info("")
                self.logger.info("=== Boss OS IPsec Secrets ===")
                self.logger.info(secrets)
                self.logger.info("")
                self.logger.info("=== Boss OS Startup Script ===")
                self.logger.info(startup_script)
            else:
                # Check if running as root
                if os.geteuid() != 0:
                    self.logger.error("Boss OS adapter requires root privileges to apply configuration")
                    return False
                
                # Create configuration directory
                config_dir = Path(self.boss_ipsec_dir)
                config_dir.mkdir(parents=True, exist_ok=True)
                
                # Write configuration files
                config_file = config_dir / 'ipsec.conf'
                secrets_file = config_dir / 'ipsec.secrets'
                startup_file = Path('/usr/local/bin/boss-ipsec-start.sh')
                
                with open(config_file, 'w') as f:
                    f.write(boss_config)
                config_file.chmod(0o644)
                
                with open(secrets_file, 'w') as f:
                    f.write(secrets)
                secrets_file.chmod(0o600)
                
                with open(startup_file, 'w') as f:
                    f.write(startup_script)
                startup_file.chmod(0o755)
                
                self.logger.info("Boss OS IPsec configuration applied successfully")
                
                # Attempt to start service
                try:
                    subprocess.run(['systemctl', 'restart', 'boss-ipsec'], 
                                 check=True, capture_output=True)
                    self.logger.info("Boss OS IPsec service restarted successfully")
                except subprocess.CalledProcessError as e:
                    self.logger.warning(f"Failed to restart service: {e}")
            
            return True
            
        except Exception as e:
            self.logger.error(f"Failed to apply Boss OS configuration: {e}")
            return False


def main():
    """Main entry point for Boss OS adapter"""
    import sys
    
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s'
    )
    logger = logging.getLogger(__name__)
    
    # Load policy from environment or argument
    policy_file = os.environ.get('POLICY_FILE', 'policy.json')
    
    if not os.path.exists(policy_file):
        logger.error(f"Policy file not found: {policy_file}")
        sys.exit(1)
    
    # Load policy
    try:
        with open(policy_file) as f:
            policy = json.load(f)
    except Exception as e:
        logger.error(f"Failed to load policy: {e}")
        sys.exit(1)
    
    # Create adapter and apply configuration
    adapter = BossOSAdapter(policy, logger)
    
    # Check if dry-run mode
    dry_run = os.environ.get('DRY_RUN', 'true').lower() == 'true'
    
    if adapter.apply_configuration(dry_run=dry_run):
        logger.info("✓ Boss OS IPsec adapter completed successfully")
        sys.exit(0)
    else:
        logger.error("✗ Boss OS IPsec adapter failed")
        sys.exit(1)


if __name__ == '__main__':
    main()
